### ISSUE TITLE
Problem with early_stopping plugin

### ISSUE THREAD

**Issue by panagiotamoraiti** [ContinualAI/clvision-challenge-2024#9]
Hello, i am trying to use early stopping plugin but my model does not stop, even when i put very low number in patience and large number in margin for testing. Could you help me with this? My code is the following:

    plugins = [
        EarlyStoppingPlugin(patience=1, val_stream_name='train', margin=5.0, metric_name='Top1_Acc_Epoch')
    ]
    Is there something wrong with the parameters i define?

**Comment by HamedHemati** [comment]
Hi @panagiotamoraiti . This could be related to an issue in the `EarlyStopping` plugin in Avalanche `0.4.0`. I assume you are using version `0.4.0` based to the environment config provided by the DevKit. I have the following suggestions:

1. Only as a test, you can create a new environment with the latest version of avalanche  (`0.5.0` or even the "master" branch) instead of `0.4.0`, and test your code there. Since the challenge DevKit is tested on Avalanche 0.4.0 on our side, we don't exactly know if there might be some incompatibility issues with other parts, so it's important to test it in a separate environment. 

2. Or, alternatively, you can copy the code from the latest version of `EarlyStopping` plugin into your local repo and directly import it there and use the local version: https://github.com/ContinualAI/avalanche/blob/master/avalanche/training/plugins/early_stopping.py
This way you can check if your issue is resolved in the latest version.

**Comment by panagiotamoraiti** [comment]
Thank you very much for your suggestion. I modified a little  the code from the latest version of EarlyStopping plugin and it works now. Thank you for your response!
